name: Server Backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
jobs:
  download-files:
    runs-on: ubuntu-latest
    environment: arma.dulliag.de
    env:
      HOST: ${{ secrets.HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.SERVER_USER }}
          password: ${{ env.SERVER_PASSWORD }}
          script: |
            cd ${{ vars.BACKUP_PATH }}
            zip -ro /home/${{ env.SERVER_USER }}/backup.zip ./
      - name: Download files
        run: |
          wget -q ftp://'${{ env.SERVER_USER }}':'${{ env.SERVER_PASSWORD }}'@${{ env.HOST }}/backup.zip
      - name: Upload postgres
        uses: actions/upload-artifact@v3
        with:
          name: backup
          path: backup.zip
